version: '3'
services:
  db:
    hostname: db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
